version: '3.8'

services:
        db:
                container_name: database
                image: mysql:5.7
                restart: unless-stopped
                environment:
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                ports: 
                        - ${MYSQL_PORT}:3306
                volumes: 
                        - ./volumes/dbdata:/var/lib/mysql
                        - ./db/initdb.d:/docker-entrypoint-initdb.d
        node:
                container_name: node
                image: node:8
                tty: true
                volumes:
                        - ./app:/var/www/html
        php:
                container_name: php
                build:
                        context: ./php
                ports:
                        - '9000:9000'
                volumes:
                        - ./app:/var/www/html
                        - ./input:/input
                depends_on:
                        - db
        nginx:
                container_name: nginx
                image: nginx:stable-alpine
                ports:
                        - ${NGINX_PORT}:80
                volumes:
                        - ./app:/var/www/html
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - php
                        - db